# Generated by Django 3.0.5 on 2023-07-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
