# Generated by Django 3.0.5 on 2023-07-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_auto_20230708_2206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Farmer',
        ),
    ]
